server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratelimiter
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        - id: sample-downstream
          uri: https://httpbin.org   # any test target
          predicates:
            - Path=/proxy/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true