{
 "title": "Rate Limiter",
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(rate_limiter_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Blocked requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (algorithm) (rate(rate_limiter_blocked_total[1m]))",
     "legendFormat": "Blocked by {{algorithm}}"
    }
   ]
  },
  {
   "title": "Block rate % (Last 5 mins)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(rate_limiter_requests_total{status=\"BLOCKED\"}[5m])) / sum(increase(rate_limiter_requests_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Top Blocked IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (clientIp) (rate_limiter_requests_total{status=\"BLOCKED\"}))"
    }
   ]
  }
 ]
}